package matrix

import (
	"bufio"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/alecthomas/chroma/v2/styles"
)

// ErrConfigFileExists is returned when attempting to initialize a config file that already exists without force.
var ErrConfigFileExists = errors.New("configuration file already exists")

// Config encapsulates runtime parameters for the Matrix rain simulation.
type Config struct {
	FPS             int
	Density         int     // 1 - 100
	SpeedScale      float64 // Multiplier for drop speeds (e.g., 0.5x - 3.0x)
	ThemeName       string
	CharSetName     string
	BoldHead        bool
	FilePath        string  // Optional path to text file
	FileContent     []byte  // Optional raw text content
	Center          bool    // Center text on screen
	Loop            bool    // Keep ambient rain falling after text settles
	TabWidth        int     // Width of tab expansion (default 4)
	SyntaxHighlight bool    // Enable syntax highlighting (default true)
	SyntaxTheme     string  // Syntax theme (e.g. monokai, dracula, nord, etc.)
	ConfigFile      string  // Path to loaded configuration file, if any
}

// DefaultConfig returns production-ready default settings.
func DefaultConfig() Config {
	return Config{
		FPS:             30,
		Density:         50,
		SpeedScale:      1.0,
		ThemeName:       "green",
		CharSetName:     string(CharSetMatrix),
		BoldHead:        true,
		TabWidth:        4,
		SyntaxHighlight: true,
		SyntaxTheme:     "monokai",
	}
}

// DefaultConfigPath returns the default path to the user configuration file (~/.mcatrc).
func DefaultConfigPath() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("failed to locate user home directory: %w", err)
	}
	return filepath.Join(home, ".mcatrc"), nil
}

// DefaultConfigFileContent returns a fully commented and structured default configuration file.
func DefaultConfigFileContent() string {
	return `# ~/.mcatrc - Configuration file for mcat
# Generated by 'mcat init'

# Target frame rate per second (10 - 120)
# Default: 30
fps = 30

# Rain drop spawn density percentage (1 - 100)
# Default: 50
density = 50

# Rain falling speed multiplier (0.2 - 3.0)
# Default: 1.0
speed = 1.0

# Rain color scheme palette
# Options: green, cyan, amber, red, white, rainbow
# Default: green
color = green

# Character set
# Options: matrix, ascii, binary, hex
# Default: matrix
charset = matrix

# Highlight leading rain character in bold
# Default: true
bold = true

# Center text horizontally and vertically on screen
# Default: false
center = false

# Keep ambient rain falling continuously around text after settling
# Default: false
loop = false

# Number of spaces for tab expansion (1 - 16)
# Default: 4
tabwidth = 4

# Enable syntax highlighting for code and structured files
# Default: true
syntax = true

# Syntax highlighting theme
# Options: monokai, dracula, nord, solarized-dark, github-dark, fruity, native
# Default: monokai
syntax-theme = monokai
`
}

// WriteDefaultConfigFile writes the default configuration template to targetPath.
// If force is false and the file exists, it returns ErrConfigFileExists.
func WriteDefaultConfigFile(targetPath string, force bool) error {
	if !force {
		if _, err := os.Stat(targetPath); err == nil {
			return ErrConfigFileExists
		}
	}

	dir := filepath.Dir(targetPath)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("failed to create directory '%s': %w", dir, err)
	}

	if err := os.WriteFile(targetPath, []byte(DefaultConfigFileContent()), 0644); err != nil {
		return fmt.Errorf("failed to write configuration file '%s': %w", targetPath, err)
	}

	return nil
}

// ParseConfig parses key-value configuration lines from an io.Reader.
func ParseConfig(r io.Reader) (map[string]string, error) {
	settings := make(map[string]string)
	scanner := bufio.NewScanner(r)
	lineNum := 0

	for scanner.Scan() {
		lineNum++
		raw := scanner.Text()
		cleaned := stripComment(raw)
		cleaned = strings.TrimSpace(cleaned)

		if cleaned == "" {
			continue
		}

		// Look for '=' or ':' separator
		sepIdx := strings.IndexAny(cleaned, "=:")
		if sepIdx < 0 {
			return nil, fmt.Errorf("line %d: invalid syntax (expected key = value): %q", lineNum, raw)
		}

		key := strings.TrimSpace(cleaned[:sepIdx])
		val := strings.TrimSpace(cleaned[sepIdx+1:])

		if key == "" {
			return nil, fmt.Errorf("line %d: missing key before separator", lineNum)
		}

		// Strip quotes if wrapped
		if len(val) >= 2 {
			if (val[0] == '"' && val[len(val)-1] == '"') || (val[0] == '\'' && val[len(val)-1] == '\'') {
				val = val[1 : len(val)-1]
			}
		}

		normKey := normalizeKey(key)
		settings[normKey] = val
	}

	if err := scanner.Err(); err != nil {
		return nil, fmt.Errorf("failed to read configuration: %w", err)
	}

	return settings, nil
}

// LoadConfigFile opens and parses a configuration file from disk.
func LoadConfigFile(path string) (map[string]string, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	return ParseConfig(f)
}

// ApplyConfigMap applies key-value configuration settings to an existing Config instance.
func ApplyConfigMap(cfg *Config, settings map[string]string) error {
	for k, v := range settings {
		switch k {
		case "fps":
			val, err := strconv.Atoi(v)
			if err != nil || val < 10 || val > 120 {
				return fmt.Errorf("invalid fps '%s': must be an integer between 10 and 120", v)
			}
			cfg.FPS = val

		case "density":
			val, err := strconv.Atoi(v)
			if err != nil || val < 1 || val > 100 {
				return fmt.Errorf("invalid density '%s': must be an integer between 1 and 100", v)
			}
			cfg.Density = val

		case "speed", "speedscale":
			val, err := strconv.ParseFloat(v, 64)
			if err != nil || val < 0.2 || val > 3.0 {
				return fmt.Errorf("invalid speed '%s': must be a float between 0.2 and 3.0", v)
			}
			cfg.SpeedScale = val

		case "color", "theme", "themename", "colorscheme":
			lower := strings.ToLower(v)
			switch lower {
			case "green", "matrix", "cyan", "blue", "amber", "yellow", "orange", "red", "white", "mono", "monochrome", "rainbow":
				cfg.ThemeName = lower
			default:
				return fmt.Errorf("unknown color palette '%s': options are green, cyan, amber, red, white, rainbow", v)
			}

		case "charset", "characterset":
			lower := strings.ToLower(v)
			switch lower {
			case "matrix", "ascii", "binary", "hex":
				cfg.CharSetName = lower
			default:
				return fmt.Errorf("unknown charset '%s': options are matrix, ascii, binary, hex", v)
			}

		case "bold", "boldhead":
			b, err := parseBool(v)
			if err != nil {
				return fmt.Errorf("invalid bold setting '%s': %w", v, err)
			}
			cfg.BoldHead = b

		case "center":
			b, err := parseBool(v)
			if err != nil {
				return fmt.Errorf("invalid center setting '%s': %w", v, err)
			}
			cfg.Center = b

		case "loop":
			b, err := parseBool(v)
			if err != nil {
				return fmt.Errorf("invalid loop setting '%s': %w", v, err)
			}
			cfg.Loop = b

		case "tabwidth", "tabspaces":
			val, err := strconv.Atoi(v)
			if err != nil || val < 1 || val > 16 {
				return fmt.Errorf("invalid tabwidth '%s': must be an integer between 1 and 16", v)
			}
			cfg.TabWidth = val

		case "syntax", "syntaxhighlight":
			b, err := parseBool(v)
			if err != nil {
				return fmt.Errorf("invalid syntax setting '%s': %w", v, err)
			}
			cfg.SyntaxHighlight = b

		case "syntaxtheme", "syntaxstyle":
			lower := strings.ToLower(v)
			style := styles.Get(lower)
			if style == nil || (style == styles.Fallback && lower != "fallback") {
				return fmt.Errorf("unknown syntax theme '%s': options include monokai, dracula, nord, solarized-dark, github-dark, fruity, native", v)
			}
			cfg.SyntaxTheme = lower

		default:
			return fmt.Errorf("unknown configuration key '%s'", k)
		}
	}
	return nil
}

// LoadAndApplyConfig reads the configuration file at path and applies it to cfg.
func LoadAndApplyConfig(cfg *Config, path string) error {
	settings, err := LoadConfigFile(path)
	if err != nil {
		return err
	}
	cfg.ConfigFile = path
	return ApplyConfigMap(cfg, settings)
}

// normalizeKey strips delimiters and converts key names to lowercase for robust matching.
func normalizeKey(k string) string {
	s := strings.ToLower(k)
	s = strings.ReplaceAll(s, "-", "")
	s = strings.ReplaceAll(s, "_", "")
	s = strings.ReplaceAll(s, " ", "")
	return s
}

// stripComment strips '#' and ';' comment markers that occur outside quotes.
func stripComment(line string) string {
	var inSingleQuote, inDoubleQuote bool
	for i, r := range line {
		switch r {
		case '\'':
			if !inDoubleQuote {
				inSingleQuote = !inSingleQuote
			}
		case '"':
			if !inSingleQuote {
				inDoubleQuote = !inDoubleQuote
			}
		case '#', ';':
			if !inSingleQuote && !inDoubleQuote {
				return line[:i]
			}
		}
	}
	return line
}

// parseBool converts strings like true/false, yes/no, on/off, 1/0 to boolean.
func parseBool(s string) (bool, error) {
	switch strings.ToLower(strings.TrimSpace(s)) {
	case "true", "1", "yes", "y", "on":
		return true, nil
	case "false", "0", "no", "n", "off":
		return false, nil
	default:
		return false, fmt.Errorf("must be true/false, yes/no, or 1/0")
	}
}
